name: Snyk Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required for GitHub Code Scanning integration
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      # Use official Snyk Action for .NET scanning
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true # Don't fail the build yet
        with:
          command: test
          args: --severity-threshold=medium --all-projects --sarif-file-output=snyk.sarif

      # Debug - List files
      - name: List SARIF files
        run: |
          echo "Files in current directory:"
          find . -name "*.sarif" -type f
          
          echo "Contents of current directory:"
          ls -la

      # Upload SARIF file to GitHub Code Scanning
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: snyk

      # Monitor project in Snyk
      - name: Monitor project in Snyk
        uses: snyk/actions/dotnet@master
        with:
          command: monitor
          args: --all-projects
          
      # Check for high severity issues
      - name: Check for high severity issues
        uses: snyk/actions/dotnet@master
        with:
          command: test
          args: --severity-threshold=high --fail-on=upgradable --all-projects
